export enum Role {
    SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
    MANAGER = 'ROLE_MANAGER',
    ADMIN = 'ROLE_ADMINE',
    USER = 'ROLE_USER',
    RHFORMATION='ROLE_RHFORMATION',
    RHRECRETEMENT='ROLE_RHRECRETEMENT',
    RHCHAUFFEUR='ROLE_RHCHAUFEUR',
    RHVISITEMEDICALE='ROLE_RHVISITE',
    SUPERADMIN='ROLE_SUPERADMIN'
} 